### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by GordonsBeard** [frostschutz/SourceLib#9]
What is this software licensed under?

I am using it for my non-profit [website](http://cafeofbrokendreams.com) ([project](https://github.com/GordonsBeard/cafe-flask/)), but I want to make sure I don't run afoul with using your software.

**Comment by frostschutz** [comment]
I guess it's the "this is no longer maintained, do whatever you want with it"-license.

**Comment by GordonsBeard** [comment]
Haha, I figured as much, just wanted to make sure!
